
server:
  port: 80
#  ssl:
#    key-password: lyh1208
#    key-store:  classpath:server.keystore
#    key-alias:  server
spring:
  datasource:
    username: root
    password: lyh120828H
    url: jdbc:mysql://localhost:3306/guanbei?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.lyh.guanbei
